### ISSUE TITLE
Move asdl-tera to a separate crate

### ISSUE THREAD

**Issue by matklad** [pasa/asdl-rs#4]
it's not clear if `tera` is the best way to approach codegen. In rust-analyzer, I am contemplating using `quote!`  instead. In any way, I think asdl library should not force clients into one particular way of doing code gen.

So I think tera-related bits should be split to a separate `asdl-tera` crate (which might be used by asdl itself for bootstrapping). It's OK to make asdl's AST Serialize, via optional `serde` feature.

**Comment by pasa** [comment]
Done it in last commit.
