### ISSUE TITLE
Reduce nom dependencies

### ISSUE THREAD

**Issue by matklad** [pasa/asdl-rs#5]
`nom` pulls in quite a few of the deps. I wonder if we can prune some of those by disabling default nom features? Additionally, given that ASDL syntax is tiny, perhaps it makes sense to just hand-roll a recursive descent parser manually?

**Comment by pasa** [comment]
I've made a commit with code structure change. I removed `lexical` feature from nom. For now it depend only from `memchr` and `version_check`. I think it's quite small dependency set.
About hand written parser. I'd prefer not to do this without a certain need. It will be third implementation :-)

**Comment by matklad** [comment]
SGTM!
