### ISSUE TITLE
Make ASDL model more idiomantic

### ISSUE THREAD

**Issue by matklad** [pasa/asdl-rs#7]
* `model::ASDL` should provide public API, and not only serialization API. In the [new](https://github.com/rust-analyzer/rust-analyzer/blob/c7d37e424f1e04f87982233f97e1e9385191b7f1/crates/ra_tools/src/boilerplate_gen.rs#L33-L160) rust-analyzer codegen, we don't make use of serialization at all

* perhaps it makes sense to keep things simple, define `Asdl` as `pub struct Asdl { pub types: Vec<Type> }` and provides accessors like `impl Asdl { fn get_type_by_name(&self, name: &str) -> Option<Type>}`. We shouldn't worry about performance, linear scan should be ok

* remove `is_prod_type`: static type of the node has  this information, no need to track it at runtime.

* instead of a bunch of `bool` fields, a `Field` should have `arity: Arity`, where `Arity` is defined as `enum Arity { Optional, Required, Repeated }`

* code organization wise, it might be useful to separate into different files public API for reading the model, from the private API for constructig the model our of AST. It's possible to have impl blocks for a struct in a file, different from the one where the said struct is defined.

**Comment by pasa** [comment]
I guess it will be difficult to design a model suited for `quote!` and template engines like `tera` equally good. I still hope to keep asdl available for other languages and templates will be preferable for it.
I suggest to keep two models in this case. One current with some changes and one as you said. In separate crates ofcourse.
By the way, the new rust-analizer codegen is really impressive. Didn't know that you can do such tricks in rust.

**Comment by pasa** [comment]
Made commit with suggested changes. f3f2e38167b80ffbe3fded047426288833eae79e
Old model was moved to the asdl_tera crate. New model placed in main asdl crate.

**Comment by matklad** [comment]
>I guess it will be difficult to design a model suited for quote! and template engines like tera equally good.

I think the solution here is to have a dead-simple *core* model, which is not specific to any code-gen solution, and is concerned with pure ASDL. Various codegen backends can then decorate the core model with something required for an engine.

**Comment by pasa** [comment]
> > I guess it will be difficult to design a model suited for quote! and template engines like tera equally good.
> 
> I think the solution here is to have a dead-simple _core_ model, which is not specific to any code-gen solution, and is concerned with pure ASDL. Various codegen backends can then decorate the core model with something required for an engine.

Agree. Your suggested model is implemented [here](https://github.com/pasa/asdl-rs/blob/master/asdl/src/model.rs).
